env:
  RCLONECONFIG_DRIVE: "ENCRYPTED[75f8315cb76f92058ed16b6c7f10fa791852aefb211e35e7042a1bd875a06c676dc5e0f85e616b3033ba2ddd25e71b9c]"
  TG_TOKEN: "ENCRYPTED[e65eea567a2b6f6b13d70a689f09786e5ce19d03f5cce4e6a98ca210fca09ab3d59e46c6eae3a7971f2051629d012708]"
  TG_CHAT_ID: "ENCRYPTED[6d4ef793f96a1d28d641983a5f3a54288790f59eb799c1f17d4abc3fc7fe21289ea69eaf98b5b0c340a2b14164d19cb1]"
  WORKDIR: "/tmp"
  EMAIL: "ENCRYPTED[7aa6306c1cc6aac701306254f2e242a05d9e9d02af964d21fd9ec9da6090b162673e122ef52f2db17a8b6beeffa35191]"
  CIRRUS_CLONE_DEPTH: "1"
  credentials: "ENCRYPTED[2e599fd6315b53b121f3846b68784458de7a3bcd7229ae6287fa8e561fb66d5471eff340ee848090fe5ae9a2b28754df]"

task:
  name: "Setting Up, Syncing, Building and Uploading"
  only_if: $CIRRUS_REPO_OWNER == 'Tiktodz'
  timeout_in: 120m
  container:
    image: anggit86/ubuntu:22.04
    cpu: 8
    memory: 32G

  Load-Ccache_background_script:
     - ./script/load_ccache.sh

  Sync-rom_script:
     - git config --global user.name "Tiktodz"
     - git config --global user.email "$EMAIL"
     - echo "$credentials" > ~/.git-credentials
     - git config --global credential.helper store --file=~/.git-credentials
     - ./script/sync.sh
     
  Build-rom_script:
     - ./script/building.sh
     
  Ccache-info_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Upload-build_script:
     - ./script/ziping.sh
